[log]
level = "INFO"

[providers]
[providers.docker]
endpoint = "tcp://dockerproxy:2375"
exposedByDefault = false
network = "self-hosted_default"
[providers.file]
filename = "/etc/traefik/dynamic.toml"

[api]
dashboard = true
debug = true
insecure = true

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.web-secure]
address = ":443"

[experimental.plugins.fail2ban]
moduleName = "github.com/tomMoulard/fail2ban"
version = "v0.7.1"
