version: "3"

networks:
  default:
    driver: bridge
  traefik:
    internal: true

services:
  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dockerproxy:
    depends_on:
      - watchtower
    environment:
      CONTAINERS: 1
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    depends_on:
      - dockerproxy
      - watchtower
    image: traefik:2.9
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - ./conf/traefik/acme.json:/acme.json
      - ./conf/traefik/traefik.toml:/traefik.toml

  mariadb:
    depends_on:
      - watchtower
    env_file: .mariadb.env
    image: mariadb:10
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql

  redis:
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    depends_on:
      - watchtower
    env_file: .redis.env
    image: redis:7
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    restart: always
    volumes:
      - ./data/redis:/data

  freshrss:
    depends_on:
      - mariadb
      - traefik
      - watchtower
    env_file: .freshrss.env
    image: freshrss/freshrss
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.freshrss-https.redirectscheme.scheme=https"
      - "traefik.http.routers.freshrss-http.entrypoints=web"
      - "traefik.http.routers.freshrss-http.rule=Host(`freshrss.sites.cfw.li`)"
      - "traefik.http.routers.freshrss-http.middlewares=freshrss-https@docker"
      - "traefik.http.routers.freshrss.entrypoints=web-secure"
      - "traefik.http.routers.freshrss.rule=Host(`freshrss.sites.cfw.li`)"
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.routers.freshrss.tls.certresolver=default"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    restart: always

  wallabag:
    depends_on:
      - mariadb
      - traefik
      - watchtower
      - redis
    env_file: .wallabag.env
    image: wallabag/wallabag
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.wallabag-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wallabag-http.entrypoints=web"
      - "traefik.http.routers.wallabag-http.rule=Host(`wallabag.sites.cfw.li`)"
      - "traefik.http.routers.wallabag-http.middlewares=wallabag-https@docker"
      - "traefik.http.routers.wallabag.entrypoints=web-secure"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.sites.cfw.li`)"
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.http.routers.wallabag.tls.certresolver=default"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    restart: always
    volumes:
      - ./data/wallabag/data:/var/www/wallabag/data
      - ./data/wallabag/images:/var/www/wallabag/web/assets/images

  nextcloud:
    depends_on:
      - mariadb
      - traefik
      - watchtower
      - redis
    env_file: .nextcloud.env
    image: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.sites.cfw.li`)"
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.sites.cfw.li`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    restart: always
    volumes:
      - ./data/nextcloud/data:/var/www/html

  gitea:
    depends_on:
      - mariadb
      - traefik
      - watchtower
      - redis
    env_file: .gitea.env
    image: gitea/gitea:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gitea-https.redirectscheme.scheme=https"
      - "traefik.http.routers.gitea-http.entrypoints=web"
      - "traefik.http.routers.gitea-http.rule=Host(`gitea.sites.cfw.li`)"
      - "traefik.http.routers.gitea-http.middlewares=gitea-https@docker"
      - "traefik.http.routers.gitea.entrypoints=web-secure"
      - "traefik.http.routers.gitea.rule=Host(`gitea.sites.cfw.li`)"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=default"
      - "traefik.http.services.gitea-http-svc.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
    restart: always
    volumes:
      - ./data/gitea:/data
